<?php
/**
 * @file
 * Hooks and main code for the Fullcalendar Views NG module.
 */

/**
 * Implements hook_views_api().
 */
function fullcalendar_views_views_api() {
  return array(
    'api' => 3,
    'path' => backdrop_get_path('module', 'fullcalendar_views') . '/views',
  );
}

/**
 * Implements hook_autoload_info().
 */
function fullcalendar_views_autoload_info() {
  return array(
    'FullcalendarViewsDisplayFeed' => 'views/fullcalendar_views_display_feed.inc',
    'FullcalendarViewsStyleCalendar' => 'views/fullcalendar_views_style_calendar.inc',
    'FullcalendarViewsStyleJson' => 'views/fullcalendar_views_style_json.inc',
  );
}

/**
 * Implements template_preprocess_views_ui_view_preview_section().
 */
function fullcalendar_views_preprocess_views_ui_view_preview_section(&$variables) {
  $view = $variables['view'];
  $plugin = $view->display_handler->get_option('style_plugin');
  if ($plugin == 'fullcalendar_view') {
    $setup  = $view->style_plugin->options['calendar_setup'];
    if (!empty($setup['event_bg_color'])) {
      // Inject an inline style tag to allow direct color preview in the views
      // admin UI.
      $inline_style = '<style>:root{';
      $inline_style .= '--fc-event-bg-color:' . $setup['event_bg_color'] . ';';
      $inline_style .= '--fc-event-border-color:' . $setup['event_bg_color'] . ';';
      $inline_style .= '--fc-event-text-color:' . $setup['event_text_color'] . ';';
      $inline_style .= '}</style>';
      $variables['content'] .= $inline_style;
    }
  }
}

/**
 * Helper function to return supported field API types.
 *
 * @see FullcalendarViewsStyleCalendar::getDateFieldCandidates()
 * @see FullcalendarViewsStyleJson::getDateFieldCandidates()
 */
function fullcalendar_views_supported_field_types() {
  return array(
    'date',
    'datetime',
    'datestamp',
    'repeating_date',
    'resource_timeslot',
  );
}

/**
 * Parse the various supported date field types into values FC can handle.
 *
 * @param array $raw_values
 *   Raw views result values provided by get_field_value().
 * @param string $type
 *   The field type as defined in hook_field_info().
 * @param bool $date_only
 *   Whether this field should be handled without time.
 * @param array $rendered_fields
 *   Array of rendered field values, usually empty at this point.
 *
 * @see FullcalendarViewsStyleCalendar::renderRow()
 * @see FullcalendarViewsStyleJson::renderRow()
 */
function fullcalendar_views_parse_date_fields(array $raw_values, $type, $date_only, &$rendered_fields) {
  switch ($type) {
    case 'date':
    case 'datetime':
      $tz = $raw_values[0]['timezone_db'];
      $start = new BackdropDateTime($raw_values[0]['value'], $tz);
      if ($date_only) {
        $rendered_fields['start'] = $start->format('Y-m-d');
      }
      else {
        $rendered_fields['start'] = $start->format('U') * 1000;
      }
      if (!empty($raw_values[0]['value2'])) {
        $end = new BackdropDateTime($raw_values[0]['value2'], $tz);
        if ($date_only) {
          $rendered_fields['end'] = $end->format('Y-m-d');
        }
        else {
          $rendered_fields['end'] = $end->format('U') * 1000;
        }
      }
      break;

    case 'datestamp':
      if ($date_only) {
        $rendered_fields['start'] = format_date($raw_values[0]['value'], 'custom', 'Y-m-d');
      }
      else {
        $rendered_fields['start'] = $raw_values[0]['value'] * 1000;
      }
      if (!empty($raw_values[0]['value2'])) {
        if ($date_only) {
          $rendered_fields['end'] = format_date($raw_values[0]['value2'], 'custom', 'Y-m-d');
        }
        else {
          $rendered_fields['end'] = $raw_values[0]['value2'] * 1000;
        }
      }
      break;

    case 'repeating_date':
      $rendered_fields['start'] = $raw_values[0]['dtstart'] * 1000;
      $rendered_fields['end'] = $raw_values[0]['dtend'] * 1000;
      break;

    case 'resource_timeslot':
      $rendered_fields['start'] = $raw_values[0]['start'] * 1000;
      $rendered_fields['end'] = $raw_values[0]['end'] * 1000;
      break;
  }
}
