name: PHPStan static code analysis
on: [pull_request]
jobs:
  phpstan:
    name: PHPStan
    runs-on: ubuntu-20.04
    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          tools: phpstan

      - uses: actions/checkout@v2

      - name: Run PHPStan
        run: phpstan analyze .
