name: PHPStan static code analysis
on: [pull_request]
jobs:
  phpstan:
    name: PHPStan
    runs-on: ubuntu-20.04
    steps:
      - name: Setup env
        run: echo "REPO_NAME=${PWD##*/}" >> $GITHUB_ENV

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          tools: phpstan

      - name: Checkout Backdrop core
        uses: actions/checkout@v2
        with:
          repository: backdrop/backdrop

      - name: Checkout module
        uses: actions/checkout@v2
        with:
          path: modules/${{ env.REPO_NAME }}

      - name: Run PHPStan
        run: |
          cd modules/${{ env.REPO_NAME }}
          phpstan analyze . -c .github/phpstan/phpstan.neon --error-format=github --no-progress
